### Get Joomla update information
GET {{endpoint}}/v1/panopticon/core/update
Authorization: Bearer {{api_token}}
X-Joomla-Token: {{api_token}}
Accept: application/vnd.api+json
User-Agent: FooBar/1.0

### Forcibly get Joomla update information
GET {{endpoint}}/v1/panopticon/core/update?force=1
Authorization: Bearer {{api_token}}
X-Joomla-Token: {{api_token}}
Accept: application/vnd.api+json
User-Agent: FooBar/1.0

### Apply the update site
POST {{endpoint}}/v1/panopticon/core/update
Authorization: Bearer {{api_token}}
X-Joomla-Token: {{api_token}}
Accept: application/vnd.api+json
User-Agent: FooBar/1.0

### Change the update source to Testing
POST {{endpoint}}/v1/panopticon/core/update
Authorization: Bearer {{api_token}}
X-Joomla-Token: {{api_token}}
Accept: application/vnd.api+json
User-Agent: FooBar/1.0
Content-Type: application/x-www-form-urlencoded

updatesource=testing

### Change the update source to Default
POST {{endpoint}}/v1/panopticon/core/update
Authorization: Bearer {{api_token}}
X-Joomla-Token: {{api_token}}
Accept: application/vnd.api+json
User-Agent: FooBar/1.0
Content-Type: application/x-www-form-urlencoded

updatesource=nochange

### Download the update
POST {{endpoint}}/v1/panopticon/core/update/download
Authorization: Bearer {{api_token}}
X-Joomla-Token: {{api_token}}
Accept: application/vnd.api+json
User-Agent: FooBar/1.0

### Download the update, chunked
POST {{endpoint}}/v1/panopticon/core/update/download/chunked
Authorization: Bearer {{api_token}}
X-Joomla-Token: {{api_token}}
Accept: application/vnd.api+json
User-Agent: FooBar/1.0

### Continue downloading the update, chunked
POST {{endpoint}}/v1/panopticon/core/update/download/chunked
Authorization: Bearer {{api_token}}
X-Joomla-Token: {{api_token}}
Accept: application/vnd.api+json
User-Agent: FooBar/1.0
Content-Type: application/x-www-form-urlencoded

url=https://update.joomla.org/releases/4.3.3/Joomla_4.3.3-Stable-Update_Package.zip&size=28745988&offset=15728640&chunk_index=7&max_time=30

### Activate the extraction script
POST {{endpoint}}/v1/panopticon/core/update/activate
Authorization: Bearer {{api_token}}
X-Joomla-Token: {{api_token}}
Accept: application/vnd.api+json
User-Agent: FooBar/1.0
Content-Type: application/x-www-form-urlencoded

basename=Joomla_4.3.0-Stable-Update_Package.zip

### Post-update code
POST {{endpoint}}/v1/panopticon/core/update/postupdate
Authorization: Bearer {{api_token}}
X-Joomla-Token: {{api_token}}
Accept: application/vnd.api+json
User-Agent: FooBar/1.0
Content-Type: application/x-www-form-urlencoded

basename=Joomla_4.3.0-Stable-Update_Package.zip

### Disable the extraction script
POST {{endpoint}}/v1/panopticon/core/update/disable
Authorization: Bearer {{api_token}}
X-Joomla-Token: {{api_token}}
Accept: application/vnd.api+json
User-Agent: FooBar/1.0
