### Get all update sites
GET {{endpoint}}/v1/panopticon/updatesites
Authorization: Bearer {{api_token}}
Accept: application/vnd.api+json
User-Agent: FooBar/1.0

### Get disabled update sites
GET {{endpoint}}/v1/panopticon/updatesites?enabled=0
Authorization: Bearer {{api_token}}
Accept: application/vnd.api+json
User-Agent: FooBar/1.0

### Get update sites for extension 448
GET {{endpoint}}/v1/panopticon/updatesites?eid[]=448
Authorization: Bearer {{api_token}}
Accept: application/vnd.api+json
User-Agent: FooBar/1.0

### Get update site with ID 303
GET {{endpoint}}/v1/panopticon/updatesite/303
Authorization: Bearer {{api_token}}
Accept: application/vnd.api+json
User-Agent: FooBar/1.0

### Modify update site 303
PATCH {{endpoint}}/v1/panopticon/updatesite/303
Authorization: Bearer {{api_token}}
Accept: application/vnd.api+json
User-Agent: FooBar/1.0
Content-Type: application/json

// IMPORTANT:
// 1. The content is a JSON document, not encoded form data
// 2. The extra_query is ALWAYS the bare key on Joomla 4 (Joomla adds the prefix and suffix automatically)
{
	"enabled": 1,
    "extra_query": "0123456789abcdef0123456789abcdef"
}

### Rebuild the update sites
POST {{endpoint}}/v1/panopticon/updatesites/rebuild
Authorization: Bearer {{api_token}}
Accept: application/vnd.api+json
User-Agent: FooBar/1.0
